# Generated by Django 2.2.6 on 2019-11-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('brand', models.TextField()),
                ('expiration_date', models.DateField()),
                ('calories', models.IntegerField()),
            ],
        ),
    ]
